### ISSUE TITLE
Typo on README- GLPv3 should be  GPLv3

### ISSUE THREAD

**Issue by shymega** [nixheads/yt-scripts#2]
The README for this repository says the "license" is the GLPv3, but I
think this is a typo, and it should be (correctly) written as GPLv3.

The link to the license is invalid, as the URL is case-sensitive-
thus, the "License" part of the URL *should* be "LICENSE", instead.

@AdrianKoshka - could you confirm this?

**Comment by AdrianKoshka** [comment]
fixed by b47292d1fb8744fb8a0598bd819852989c3db1ff
